theme: jekyll-theme-slate
title: Breaking the boundaries of ChromeOS - A guide
template:
  params:
    bootswatch: flatly
reference:
  - title: Exported Functions
    desc: ~
    contents:
      - '`aaaa`'
      - '`bbbb`'
navbar:
  type: inverse
  left:
    - icon: 
      href: index.html
    - text: "faq"
      icon: fa-question-circle-o
      href: articles/faq.html
